export function dashboardPage() {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>World Proof Gateway</title>
<style>
:root{color-scheme:dark;font:100%/1.48 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#08120e;color:#f5f6ed}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% -10%,#214c36,#08120e 55%);min-height:100svh}main{width:min(100%,680px);margin:auto;padding:1rem 1rem 4rem}h1{letter-spacing:-.045em;font-size:clamp(2.15rem,10vw,3.5rem);line-height:1;margin:1.4rem 0 .6rem}.eyebrow,.label{font-size:.72rem;letter-spacing:.12em;text-transform:uppercase;font-weight:800;color:#bdce9d}.card{background:rgba(17,38,26,.9);border:1px solid rgba(176,204,137,.3);box-shadow:0 18px 55px rgba(0,0,0,.24);border-radius:1.2rem;padding:1rem;margin:1rem 0}.muted,small{color:#b9c6b3}input,select,button{box-sizing:border-box;width:100%;margin:.34rem 0;padding:.8rem .9rem;border-radius:.75rem;border:1px solid #58775b;font:inherit}input,select{background:#0a1a11;color:#f5f6ed}button{border:0;background:#d7e478;color:#142010;font-weight:850;cursor:pointer;box-shadow:0 3px 0 #84923a;transition:transform .15s ease}button:active{transform:translateY(2px);box-shadow:0 1px 0 #84923a}#project-list{list-style:none;padding:0;margin:.75rem 0}#project-list li{padding:.8rem 0;border-bottom:1px solid rgba(176,204,137,.17)}#project-list li:last-child{border:0}.notice{border-left:3px solid #d7e478;padding-left:.75rem}.status{min-height:1.55rem;color:#d7e478}@media(prefers-reduced-motion:reduce){button{transition:none}}
</style></head><body><main>
<p class="eyebrow">World Proof Gateway</p><h1>Developer console</h1><p class="muted">Create a Portal-configured project, buy request credits and keep every RP signing key encrypted server-side.</p>
<section class="card" id="login"><h2>Sign in with World ID</h2><p class="muted">A verified World ID creates your developer account automatically.</p><button id="world-login">Verify with World ID</button><p class="status" id="status" role="status"></p></section>
<section class="card" id="projects" hidden><p class="eyebrow">Your workspace</p><h2>Your projects</h2><ul id="project-list"></ul><h2>Create a project</h2><p class="notice muted">Create the App, RP and action in the World Developer Portal first. Paste the Portal-issued RP signing key once. The Gateway encrypts it and never returns it.</p><form id="create"><label class="label">Project ID</label><input name="id" required pattern="[a-z0-9][a-z0-9-]{2,47}" placeholder="my-mini-app"><input name="appId" required placeholder="World App ID (app_...)" autocomplete="off"><input name="rpId" required placeholder="World RP ID (rp_...)" autocomplete="off"><input name="rpSigningKey" required type="password" autocomplete="off" pattern="0x[0-9a-fA-F]{64}" placeholder="Portal-issued RP signing key (0x...)" aria-label="Portal-issued RP signing key"><input name="action" required placeholder="Action, e.g. human-access-v1"><input name="origin" required type="url" placeholder="https://your-mini-app.example"><select name="environment"><option value="production">Production</option><option value="staging">Staging</option></select><select name="signalPolicy"><option value="none">No signal</option><option value="wallet-address">Wallet-address signal</option></select><button>Create encrypted project</button></form><p class="status" id="create-status" role="status"></p><h2>Credits</h2><form id="buy"><input name="projectId" required placeholder="Your project ID to credit"><button>Buy 5,000 requests · 1 WLD</button></form><p class="status" id="buy-status" role="status"></p></section>
</main><script src="/assets/idkit.global.js"></script><script type="module">
import { MiniKit, Tokens, tokenToDecimals } from '/assets/minikit.js?build=0598e96';
const WLD_PAY_AMOUNT=tokenToDecimals(1,Tokens.WLD).toString();
const status=document.querySelector('#status'),login=document.querySelector('#login'),projects=document.querySelector('#projects');
const api=async(path,options={})=>{const response=await fetch(path,options);const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data};
const headers=()=>({'content-type':'application/json'});
async function ensureMiniKit(context){if(MiniKit.isInstalled())return;const config=context||await api('/v1/owner/proof-context',{method:'POST'}),installation=MiniKit.install(config.app_id);if(!installation.success)throw new Error('World App bridge is unavailable. Reopen this Mini App from World.');}
async function refresh(){try{const data=await api('/v1/owner/projects');login.hidden=true;projects.hidden=false;const list=document.querySelector('#project-list');list.replaceChildren();if(!data.projects.length){const item=document.createElement('li');item.textContent='No projects yet.';list.append(item);return}for(const project of data.projects){const item=document.createElement('li'),title=document.createElement('b'),meta=document.createElement('small');title.textContent=project.id;meta.textContent=project.appId+' · '+project.rpId+' · '+project.action;item.append(title,document.createElement('br'),meta);list.append(item)}}catch{}}
async function signIn(){status.textContent='Preparing World ID request…';const context=await api('/v1/owner/proof-context',{method:'POST'});await ensureMiniKit(context);if(!globalThis.IDKit)throw new Error('World ID module could not load. Reload the Mini App and try again.');status.textContent='Open World ID confirmation…';const request=await globalThis.IDKit.request({app_id:context.app_id,action:context.action,rp_context:context.rp_context,environment:context.environment,allow_legacy_proofs:true}).preset(globalThis.IDKit.orbLegacy());const completed=await request.pollUntilCompletion({timeout:120000});if(!completed.success)throw new Error(completed.error==='timeout'?'World ID confirmation timed out. Try again.':'World ID verification was not completed.');await api('/v1/owner/proofs',{method:'POST',headers:headers(),body:JSON.stringify({idkitResponse:completed.result})});await refresh();status.textContent='Owner session ready.'}
document.querySelector('#world-login').onclick=async()=>{try{await signIn()}catch(error){status.textContent=error.message||'World ID verification failed.'}};
document.querySelector('#create').onsubmit=async(event)=>{event.preventDefault();const form=new FormData(event.currentTarget),out=document.querySelector('#create-status'),messages={https_required:'Secure proxy header missing. Please retry after the gateway proxy is configured for HTTPS.',invalid_tenant_id:'Project ID: 3–48 lowercase letters, numbers or hyphens.',invalid_tenant_world_config:'Check the World App ID, RP ID and action.',invalid_tenant_environment:'Choose Production or Staging.',invalid_tenant_origins:'Origin must be a valid HTTPS URL.',invalid_tenant_signal_policy:'Choose a supported signal policy.',tenant_rp_signing_key_required:'Enter the 32-byte RP signing key from the World Developer Portal.',tenant_identifier_already_exists:'This project ID, World App ID or RP ID already exists.'};try{await api('/v1/owner/projects',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({id:form.get('id'),appId:form.get('appId'),rpId:form.get('rpId'),rpSigningKey:form.get('rpSigningKey'),action:form.get('action'),allowedOrigins:[form.get('origin')],environment:form.get('environment'),signalPolicy:form.get('signalPolicy')})});out.textContent='Project created. Its Portal-issued RP signing key is encrypted and cannot be retrieved.';event.currentTarget.reset();await refresh()}catch(error){out.textContent=messages[error.message]||'Project could not be created. Try again or contact support.'}};
document.querySelector('#buy').onsubmit=async(event)=>{event.preventDefault();const out=document.querySelector('#buy-status'),projectId=new FormData(event.currentTarget).get('projectId'),messages={world_payment_mismatch:'The payment amount did not match 1 WLD. No requests were credited.',world_payment_not_accepted:'World could not accept this payment yet. Please try again later.',payment_reference_expired:'This payment request expired. Start a new checkout.'};try{out.textContent='Creating payment…';await ensureMiniKit();const order=await api('/v1/billing/intents',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId})});if(order.token_amount!==WLD_PAY_AMOUNT)throw new Error('Payment plan is not ready. Reload the Mini App.');const payment=await MiniKit.pay({reference:order.reference,to:order.to,tokens:[{symbol:Tokens.WLD,token_amount:WLD_PAY_AMOUNT}],description:order.description,fallback:()=>{throw new Error('Open this checkout in World App.')}});if(payment.executedWith!=='minikit'||!payment.data?.transactionId)throw new Error('Payment not completed.');const result=await api('/v1/billing/confirmations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reference:order.reference,transactionId:payment.data.transactionId})});out.textContent=result.request_credits+' requests credited.'}catch(error){out.textContent=messages[error.message]||error.message||'Checkout failed.'}};
refresh();
</script></body></html>`;
}
