const escapeHtml = (value) => String(value).replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]);

export function onboardingPage({ demoMode, billingPlan = {} }) {
  const badge = demoMode ? "DEMO — no real proof verification or crediting" : "PRIVATE BETA — production verification requires configured World secrets and database";
  const checkoutEnabled = !demoMode && billingPlan.charging_enabled === true;
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>World Proof Gateway | Private beta</title>
<style>:root{color-scheme:dark;font:100%/1.5 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#08120e;color:#f5f6ed}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 50% -10%,#214c36,#08120e 54%);min-height:100svh}main{width:min(100%,680px);margin:auto;padding:clamp(1rem,4vw,2.5rem) 1rem 4rem}.mast{padding:1rem 0 1.5rem}.eyebrow{letter-spacing:.13em;text-transform:uppercase;font-size:.72rem;color:#b8c99a;font-weight:800}.badge{display:inline-flex;border:1px solid #6f8459;background:#25361f;color:#eaf5c5;border-radius:999px;padding:.32rem .6rem;font-size:.72rem;font-weight:800}.card{background:rgba(14,32,23,.88);border:1px solid rgba(188,212,143,.25);box-shadow:0 18px 55px rgba(0,0,0,.25);border-radius:1.35rem;padding:1.15rem;margin:.9rem 0}.price{font-size:clamp(2.45rem,11vw,4rem);line-height:1;letter-spacing:-.055em;margin:.35rem 0}.price small{font-size:.42em;letter-spacing:-.02em;color:#d7e3b4}.muted{color:#aab7a4}.grid{display:grid;grid-template-columns:1fr 1fr;gap:.75rem;margin:1rem 0}.stat{border-radius:1rem;padding:.8rem;background:#152b1e;border:1px solid rgba(188,212,143,.14)}.stat b{display:block;font-size:1.35rem}.label{font-size:.72rem;text-transform:uppercase;letter-spacing:.11em;color:#b6c79b;font-weight:800}input,button{font:inherit}input{width:100%;margin:.7rem 0;padding:.82rem 1rem;background:#0b1c13;color:#f7f8f2;border:1px solid #45664a;border-radius:.8rem;outline-offset:3px}button{width:100%;padding:.9rem 1rem;border:0;border-radius:.85rem;background:#d7e478;color:#172112;font-weight:850;cursor:pointer;box-shadow:0 4px 0 #84923a;transition:transform .15s ease,filter .15s ease}button:active{transform:translateY(3px);box-shadow:0 1px 0 #84923a}button:disabled{filter:grayscale(1);opacity:.55;cursor:not-allowed}#checkout-status{min-height:1.6rem;color:#d7e3b4;font-size:.9rem}.fine{font-size:.8rem;color:#93a28f}@media(prefers-reduced-motion:reduce){button{transition:none}}@media(min-width:700px){main{padding-top:4rem}.grid{gap:1rem}.card{padding:1.5rem}}</style></head>
<body><main><header class="mast"><span class="badge">${escapeHtml(badge)}</span><p class="eyebrow">Proof infrastructure</p><h1>World Proof<br>Gateway</h1><p class="muted">Private control plane for static, World-ID-enabled Mini Apps.</p></header>
<section class="card" aria-labelledby="buy-title"><span class="label">Request pack</span><h2 id="buy-title" class="price">1 WLD <small>/ 5,000 requests</small></h2><p id="billing" class="muted">${escapeHtml(billingPlan.message || "Loading billing configuration…")}</p><div class="grid"><div class="stat"><span class="label">Network</span><b>World Chain</b></div><div class="stat"><span class="label">Settlement</span><b>On-chain</b></div></div><form id="checkout"><label class="label" for="project-id">Project ID to credit</label><input id="project-id" name="projectId" required pattern="[a-z0-9][a-z0-9-]{2,47}" placeholder="your-project-id" autocomplete="off"><button id="checkout-button" ${checkoutEnabled ? "" : "disabled"}>Buy 5,000 requests · 1 WLD</button></form><p id="checkout-status" role="status"></p><p class="fine">The payment is credited only after server-side verification against the World Developer Portal.</p></section>
<section class="card"><span class="label">Build safely</span><h2>Proofs stay server-side.</h2><p class="muted">Each tenant uses its own RP signing key, encrypted in the Gateway database. Static Mini Apps only receive signed contexts and verification results.</p></section>
</main><script type="module">
const status=document.querySelector('#checkout-status'),button=document.querySelector('#checkout-button');
const message=(v)=>status.textContent=v;
let MiniKit,Tokens;
try{({MiniKit}=await import('https://cdn.jsdelivr.net/npm/@worldcoin/minikit-js@2.0.3/+esm'));({Tokens}=await import('https://cdn.jsdelivr.net/npm/@worldcoin/minikit-js@2.0.3/commands/+esm'));MiniKit.install();}catch{message('Open this checkout in World App to pay with WLD.');}
document.querySelector('#checkout').addEventListener('submit',async(e)=>{e.preventDefault();if(!MiniKit)return message('MiniKit is available only in World App.');button.disabled=true;try{message('Creating secure payment reference…');const projectId=new FormData(e.currentTarget).get('projectId');const intent=await fetch('/v1/billing/intents',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({projectId})});const order=await intent.json();if(!intent.ok)throw new Error(order.error||'Unable to create payment.');message('Confirm payment in World App…');const payment=await MiniKit.pay({reference:order.reference,to:order.to,tokens:[{symbol:Tokens.WLD,token_amount:order.token_amount}],description:order.description,fallback:()=>message('Open this checkout in World App to complete payment.')});if(payment.executedWith!=='minikit'||!payment.data?.transactionId)throw new Error('Payment was not completed.');message('Verifying on World Chain…');const confirmation=await fetch('/v1/billing/confirmations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({reference:order.reference,transactionId:payment.data.transactionId})});const result=await confirmation.json();if(!confirmation.ok)throw new Error(result.error||'Payment is still pending.');message(String(result.request_credits).toLocaleString()+' requests credited. Remaining: '+String(result.remaining_requests).toLocaleString()+'.');}catch(error){message(error.message||'Checkout could not be completed.');}finally{button.disabled=false;}});
</script></body></html>`;
}
